/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UcSideDrawer {
    'open': boolean;
    'openSideDrawer': () => Promise<void>;
    'title': string;
  }
  interface UcStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLUcSideDrawerElement extends Components.UcSideDrawer, HTMLStencilElement {}
  var HTMLUcSideDrawerElement: {
    prototype: HTMLUcSideDrawerElement;
    new (): HTMLUcSideDrawerElement;
  };

  interface HTMLUcStockPriceElement extends Components.UcStockPrice, HTMLStencilElement {}
  var HTMLUcStockPriceElement: {
    prototype: HTMLUcStockPriceElement;
    new (): HTMLUcStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'uc-side-drawer': HTMLUcSideDrawerElement;
    'uc-stock-price': HTMLUcStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface UcSideDrawer extends JSXBase.HTMLAttributes<HTMLUcSideDrawerElement> {
    'open'?: boolean;
    'title'?: string;
  }
  interface UcStockPrice extends JSXBase.HTMLAttributes<HTMLUcStockPriceElement> {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'uc-side-drawer': UcSideDrawer;
    'uc-stock-price': UcStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


